### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Water-Moon** [Harleyoc1/DynamicTreesHeatAndClimate#3]
The season provider class in this mod's code ([here](https://github.com/Harleyoc1/DynamicTreesHeatAndClimate/blob/5bf8380e6f1ca35da5af50d2464e5e142ceaee2c/src/main/java/com/harleyoconnor/dynamictreeshnc/seasons/SeasonProviderHeatAndClimate.java#L16)) doesn't match the method signature of the interface in the dynamic trees base mod ([here](https://github.com/ferreusveritas/DynamicTrees/blob/07a150b27517a8593459cb804ac78fb67be6efe9/src/main/java/com/ferreusveritas/dynamictrees/seasons/ISeasonProvider.java#L19)). It is supposed to take in two parameters - world and position, but the method in this mod's code only take the world parameter.

And it crashed the game. The crash log is also attached.
[crash-2020-12-06_17.54.46-server.txt](https://github.com/Harleyoc1/DynamicTreesHeatAndClimate/files/5649710/crash-2020-12-06_17.54.46-server.txt)

**Comment by Microsoft6477** [comment]
getting same error

**Comment by Water-Moon** [comment]
> 
> 
> getting same error

Yup, that's because of the overridden method mismatch... hope it could be fixed soon :D

**Comment by GalaxyS7** [comment]
same error

DynamicTreesHNC-1.12.2-2.0.1.jar
HeatAndClimateMod_1.12.2-3.6.2.jar
HeatAndClimateLib_1.12.2-3.6.2.jar

**Comment by shinoharatsuru** [comment]
Crash same error.

**Comment by Harleyoc1** [comment]
Looks like it should be a simple fix, I'll take a look now.

**Comment by supermassimo** [comment]
Fixed in [2.0.2](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-heat-and-climate/files/3272028)
